version: "3"

services:
  zipkin:
    image: openzipkin/zipkin:latest
    restart: always
    ports:
      - "9411:9411"

  otelcol:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./configs/otel-collector.yaml:/etc/otel/config.yaml
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - 4317:4317
      - 55679:55679

  servico-a:
    container_name: servico-a
    build:
      context: ./servico-a
      dockerfile: ./Dockerfile
    ports:
      - 8070:8070
      
  servico-b:
    container_name: servico-b
    build:
      context: ./servico-b
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080